<template>
  <div id="app" >
    <div id="nav">
      <Bubble :closeOnNavigation="true" >
        <router-link to="/#home"><span>Home</span></router-link>
        <router-link to="/#info"><span>O Nas</span></router-link>
        <router-link to="/#zespol"><span>Zespół</span></router-link>
        <router-link to="/#concerts"><span>Koncerty</span></router-link>
        <router-link to="/#music"><span>Rzuć Uchem</span></router-link>
        <router-link to="/#gallery"><span>Rzuć Okiem</span></router-link>
        <router-link to="/#dowload"><span>Prasa i Rider</span></router-link>
        <router-link to="/contact"><span>Kontakt</span></router-link>
      </Bubble>
      <h1>Tarło</h1>
      <div id="ytlogo" data-aos="fade-down-left"  >
        <a href="https://www.youtube.com/channel/UCAK10cFtn2SoFgZu-TsP1Tg" target="_blank" >
          <img class="heartbeat" alt="tarlo" src="./assets/yttop.png" />
        </a>
      </div>    
    </div>
    <div id="content"  >
      <div>
        <router-view/>
      </div>
    </div>
  </div>
</template>

<script>
import './styles.scss'
import { Bubble } from 'vue-burger-menu'  

export default {
  components: {
    Bubble 
  }
}
</script>


<style lang="scss">

/* MOBILE */
h1 {
  text-align: center;
  font-size:60px;
  color: #424242;
  margin: 0;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  }

#ytlogo{
  position:fixed;
  left:80%;
  height: 7%;
  width: 16%;
  top:25px;
}

img, a {
  position:relative;
  width: 100%;
  height: 100%;
}

#app{
      padding: 0;
      margin: 0;
      height: 100%;
    }

#nav {
      margin: 0;
      padding: 0;
      position: fixed;
      width: 100%;
      height:  96px;
      z-index: 99;
      background:#1F1F1F;
      top:0;
    }

#content {
      float: left;
      margin-top:96px;
      padding: 0;
      width: calc(100% - 0px) ;
    }

//Burger
.bm-burger-button {
      position: fixed;
      width: 36px;
      height: 30px;
      left: 36px;
      top: 36px;
      cursor: pointer;
    }
    .bm-burger-bars {
      background-color: #CFD8DC;
    }
    .line-style {
      position: absolute;
      height: 20%;
      left: 0;
      right: 0;
    }
    .cross-style {
      position: absolute;
      top: 12px;
      right: 2px;
      cursor: pointer;
    }
    .bm-cross {
      background: white;
    }
    .bm-cross-button {
      height: 24px;
      width: 24px;
    }
    .bm-menu {
      height: 100%; /* 100% Full-height */
      width: 0; /* 0 width - change this with JavaScript */
      position: fixed; /* Stay in place */
      z-index: 1000; /* Stay on top */
      top: 0;
      left: 0;
      background-color: #424242; /* Black*/
      overflow-x: hidden; /* Disable horizontal scroll */
      padding-top: 60px; /* Place content 60px from the top */
      transition: 0.5s; /*0.5 second transition effect to slide in the sidenav*/
    }

    .bm-overlay {
      background: #424242;
    }
    .bm-item-list {
      font-color: white;
      margin-left: 10%;
      font-size: 50px;
      text-decoration: none;
    }
    .bm-item-list > * {
      display: flex;
      text-decoration: none;
      padding: 0.7em;
    }
    .bm-item-list > * > span {
      margin-left: 10px;
      font-weight: 700;
      color: white;
    }


//yt animacja

.heartbeat {
	-webkit-animation: heartbeat 5s ease-in-out infinite both;
	        animation: heartbeat 5s ease-in-out infinite both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-3-17 23:43:42
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation heartbeat
 * ----------------------------------------
 */
@-webkit-keyframes heartbeat {
  from {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-transform-origin: center center;
            transform-origin: center center;
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  2% {
    -webkit-transform: scale(0.91);
            transform: scale(0.91);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  4% {
    -webkit-transform: scale(0.98);
            transform: scale(0.98);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  6% {
    -webkit-transform: scale(0.87);
            transform: scale(0.87);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  8% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
}
@keyframes heartbeat {
  from {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-transform-origin: center center;
            transform-origin: center center;
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  2% {
    -webkit-transform: scale(0.91);
            transform: scale(0.91);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  4% {
    -webkit-transform: scale(0.98);
            transform: scale(0.98);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  6% {
    -webkit-transform: scale(0.87);
            transform: scale(0.87);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  8% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
}

</style>
